### ISSUE TITLE
能支持墙内的翻译吗

### ISSUE THREAD

**Issue by tangxiadi** [millionart/WinPopclip#3]
google搜索替换成baidu搜索倒是会改，但是google翻译那一段不太会改

**Comment by millionart** [comment]
百度的代码因为写的很混乱，所以很难定位翻译结果元素，没办法

**Comment by tangxiadi** [comment]
可以考虑百度翻译的api啊，目前key是免费申请的，让用户自己在config文件里填写key就好了

**Comment by millionart** [comment]
实在没有心力去做，这个脚本其实是自用的，更多作用是抛砖引玉，因为太多人说Windows上实现不了或者不值得实现popclip，而且autohotkey可能做不到api什么的
