### ISSUE TITLE
期待增加多屏幕支持

### ISSUE THREAD

**Issue by elonj** [millionart/WinPopclip#7]
现在（0.7）的版本在多屏幕下使用时，如果选中的文字在第一个屏幕，选择条在选中的文字的上方，没有问题。但如果选中的文字不在第一个屏幕，选择条只会出现在第一个屏幕的边缘，而不是在选中文字的上方。希望可以增加多屏幕的支持。非常感谢

**Comment by millionart** [comment]
已修复
