### ISSUE TITLE
乱码，求解决

### ISSUE THREAD

**Issue by xulei-shl** [millionart/WinPopclip#9]
![image](https://user-images.githubusercontent.com/13896259/103965899-ae3cd300-5199-11eb-821e-a33ef47a9df8.png)
 乱码，怎么解决呢

**Comment by millionart** [comment]
安装 Utf8 版 Autohotkey

**Comment by msongz** [comment]
另存脚本为带bom的utf8就行

**Comment by millionart** [comment]
新版本已修复
